INSERT INTO provinces (id, name, slug)
VALUES
	('11','Aceh','aceh'),
	('12','Sumatera Utara','sumatera-utara'),
	('13','Sumatera Barat','sumatera-barat'),
	('14','Riau','riau'),
	('15','Jambi','jambi'),
	('16','Sumatera Selatan','sumatera-selatan'),
	('17','Bengkulu','bengkulu'),
	('18','Lampung','lampung'),
	('19','Kepulauan Bangka Belitung','kepulauan-bangka-belitung'),
	('21','Kepulauan Riau','kepulauan-riau'),
	('31','DKI Jakarta','dki-jakarta'),
	('32','Jawa Barat','jawa-barat'),
	('33','Jawa Tengah','jawa-tengah'),
	('34','DI Yogyakarta','di-yogyakarta'),
	('35','Jawa Timur','jawa-timur'),
	('36','Banten','banten'),
	('51','Bali','bali'),
	('52','Nusa Tenggara Barat','nusa-tenggara-barat'),
	('53','Nusa Tenggara Timur','nusa-tenggara-timur'),
	('61','Kalimantan Barat','kalimantan-barat'),
	('62','Kalimantan Tengah','kalimantan-tengah'),
	('63','Kalimantan Selatan','kalimantan-selatan'),
	('64','Kalimantan Timur','kalimantan-timur'),
	('65','Kalimantan Utara','kalimantan-utara'),
	('71','Sulawesi Utara','sulawesi-utara'),
	('72','Sulawesi Tengah','sulawesi-tengah'),
	('73','Sulawesi Selatan','sulawesi-selatan'),
	('74','Sulawesi Tenggara','sulawesi-tenggara'),
	('75','Gorontalo','gorontalo'),
	('76','Sulawesi Barat','sulawesi-barat'),
	('81','Maluku','maluku'),
	('82','Maluku Utara','maluku-utara'),
	('91','Papua Barat','papua-barat'),
	('94','Papua','papua');
